### ISSUE TITLE
Errors running npm run build

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3-server#2]
```
~/g/i/in3-node (develop>) npm run build

> in3-server@0.1.0 build /home/ligi/git/in3/in3-node
> tsc -p .

src/chains/BaseHandler.ts(20,71): error TS2307: Cannot find module 'in3-common'.
src/chains/BaseHandler.ts(22,19): error TS2307: Cannot find module 'axios'.
src/chains/BaseHandler.ts(30,26): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
src/chains/BaseHandler.ts(63,20): error TS2339: Property 'on' does not exist on type 'Watcher'.
src/chains/initHandler.ts(21,22): error TS2307: Cannot find module 'in3-common'.
src/chains/initHandler.ts(23,21): error TS2307: Cannot find module 'fs'.
src/chains/initHandler.ts(25,23): error TS2307: Cannot find module 'crypto'.
src/chains/initHandler.ts(26,26): error TS2307: Cannot find module 'ethereumjs-util'.
src/chains/initHandler.ts(51,33): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(51,55): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(58,40): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(58,62): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(62,28): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(63,32): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(67,93): error TS2304: Cannot find name 'Buffer'.
src/chains/initHandler.ts(68,32): error TS2304: Cannot find name 'Buffer'.
src/chains/nodeListUpdater.ts(22,85): error TS2307: Cannot find module 'in3-common'.
src/chains/nodeListUpdater.ts(24,46): error TS2307: Cannot find module 'ethereumjs-util'.
src/chains/nodeListUpdater.ts(26,22): error TS2307: Cannot find module 'ethereumjs-abi'.
src/chains/nodeListUpdater.ts(104,15): error TS2304: Cannot find name 'Buffer'.
src/chains/nodeListUpdater.ts(122,15): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(21,44): error TS2307: Cannot find module 'in3-common'.
src/chains/signatures.ts(23,57): error TS2307: Cannot find module 'ethereumjs-util'.
src/chains/signatures.ts(27,26): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
src/chains/signatures.ts(94,37): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(94,53): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(99,23): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(128,33): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(128,49): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(249,29): error TS2304: Cannot find name 'Buffer'.
src/chains/signatures.ts(249,45): error TS2304: Cannot find name 'Buffer'.
src/chains/watch.ts(20,21): error TS2307: Cannot find module 'fs'.
src/chains/watch.ts(21,30): error TS2307: Cannot find module 'events'.
src/chains/watch.ts(22,31): error TS2307: Cannot find module 'in3-common'.
src/chains/watch.ts(23,43): error TS2307: Cannot find module 'ethereumjs-util'.
src/chains/watch.ts(74,10): error TS2339: Property 'on' does not exist on type 'Watcher'.
src/chains/watch.ts(151,10): error TS2339: Property 'emit' does not exist on type 'Watcher'.
src/chains/watch.ts(175,32): error TS2339: Property 'emit' does not exist on type 'Watcher'.
src/modules/eth/EthHandler.ts(20,55): error TS2307: Cannot find module 'in3-common'.
src/modules/eth/EthHandler.ts(29,20): error TS2304: Cannot find name 'require'.
src/modules/eth/EthHandler.ts(175,54): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/EthHandler.ts(217,55): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/EthHandler.ts(218,15): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/api.ts(2,26): error TS2307: Cannot find module 'ethereumjs-abi'.
src/modules/eth/api.ts(3,69): error TS2307: Cannot find module 'ethereumjs-util'.
src/modules/eth/api.ts(4,24): error TS2307: Cannot find module 'in3-common'.
src/modules/eth/api.ts(6,47): error TS2307: Cannot find module '@ethersproject/abi'.
src/modules/eth/api.ts(264,9): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/api.ts(269,48): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/api.ts(285,57): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/api.ts(341,48): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/api.ts(385,57): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/evm_run.ts(20,21): error TS2307: Cannot find module 'ethereumjs-vm'.
src/modules/eth/evm_run.ts(21,26): error TS2307: Cannot find module 'ethereumjs-account'.
src/modules/eth/evm_run.ts(22,24): error TS2307: Cannot find module 'ethereumjs-block'.
src/modules/eth/evm_run.ts(23,23): error TS2307: Cannot find module 'merkle-patricia-tree'.
src/modules/eth/evm_run.ts(24,21): error TS2307: Cannot find module 'ethereumjs-util'.
src/modules/eth/evm_run.ts(25,33): error TS2307: Cannot find module 'in3-common'.
src/modules/eth/evm_run.ts(36,11): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/evm_run.ts(50,14): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/evm_run.ts(149,36): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(1,23): error TS2307: Cannot find module 'merkle-patricia-tree'.
src/modules/eth/merkle.ts(2,28): error TS2307: Cannot find module 'worker_threads'.
src/modules/eth/merkle.ts(3,22): error TS2307: Cannot find module 'in3-common'.
src/modules/eth/merkle.ts(10,85): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(20,22): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(20,44): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(26,28): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(27,30): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/merkle.ts(29,34): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(20,95): error TS2307: Cannot find module 'in3-common'.
src/modules/eth/proof.ts(22,40): error TS2307: Cannot find module 'ethereumjs-util'.
src/modules/eth/proof.ts(23,23): error TS2307: Cannot find module 'merkle-patricia-tree'.
src/modules/eth/proof.ts(24,21): error TS2307: Cannot find module 'in3-trie'.
src/modules/eth/proof.ts(31,20): error TS2304: Cannot find name 'require'.
src/modules/eth/proof.ts(171,56): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(171,71): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(171,88): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(171,110): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(185,26): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(202,18): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(202,40): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(213,22): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/proof.ts(216,24): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(1,24): error TS2307: Cannot find module 'worker_threads'.
src/modules/eth/threadPool.ts(2,22): error TS2307: Cannot find module 'os'.
src/modules/eth/threadPool.ts(17,41): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(17,56): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(17,73): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(17,95): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(23,38): error TS2304: Cannot find name 'Buffer'.
src/modules/eth/threadPool.ts(50,34): error TS2304: Cannot find name 'process'.
src/modules/eth/threadPool.ts(101,1): error TS2304: Cannot find name 'module'.
src/modules/ipfs/IPFSHandler.ts(20,27): error TS2307: Cannot find module 'in3-common'.
src/modules/ipfs/IPFSHandler.ts(22,85): error TS2307: Cannot find module 'axios'.
src/modules/ipfs/IPFSHandler.ts(32,37): error TS2304: Cannot find name 'Buffer'.
src/modules/ipfs/IPFSHandler.ts(57,33): error TS2304: Cannot find name 'Buffer'.
src/modules/ipfs/IPFSHandler.ts(77,19): error TS2304: Cannot find name 'Buffer'.
src/modules/ipfs/IPFSHandler.ts(98,32): error TS2304: Cannot find name 'Buffer'.
src/modules/ipfs/IPFSHandler.ts(100,13): error TS2304: Cannot find name 'Buffer'.
src/modules/ipfs/IPFSHandler.ts(100,44): error TS2304: Cannot find name 'Buffer'.
src/server/config.ts(20,21): error TS2307: Cannot find module 'fs'.
src/server/config.ts(21,22): error TS2307: Cannot find module 'in3-common'.
src/server/config.ts(23,24): error TS2307: Cannot find module 'args'.
src/server/config.ts(98,36): error TS2304: Cannot find name 'process'.
src/server/poa.ts(21,80): error TS2307: Cannot find module 'in3-common'.
src/server/poa.ts(25,25): error TS2307: Cannot find module 'secp256k1'.
src/server/poa.ts(26,38): error TS2307: Cannot find module 'ethereumjs-util'.
src/server/poa.ts(30,16): error TS2304: Cannot find name 'require'.
src/server/poa.ts(304,18): error TS2304: Cannot find name 'Buffer'.
src/server/rpc.ts(21,51): error TS2307: Cannot find module 'in3-common'.
src/server/rpc.ts(23,19): error TS2307: Cannot find module 'axios'.
src/server/server.ts(27,16): error TS2304: Cannot find name 'require'.
src/server/server.ts(29,22): error TS2307: Cannot find module 'koa'.
src/server/server.ts(30,29): error TS2307: Cannot find module 'koa-bodyparser'.
src/server/server.ts(31,25): error TS2307: Cannot find module 'koa-router'.
src/server/server.ts(35,37): error TS2307: Cannot find module 'in3-common'.
src/server/server.ts(40,5): error TS2304: Cannot find name 'process'.
src/server/server.ts(42,18): error TS2304: Cannot find name 'process'.
src/server/server.ts(43,22): error TS2304: Cannot find name 'process'.
src/server/server.ts(44,26): error TS2304: Cannot find name 'process'.
src/server/server.ts(51,3): error TS2304: Cannot find name 'process'.
src/server/server.ts(54,1): error TS2304: Cannot find name 'process'.
src/server/server.ts(55,1): error TS2304: Cannot find name 'process'.
src/server/server.ts(57,1): error TS2304: Cannot find name 'process'.
src/server/server.ts(59,7): error TS2304: Cannot find name 'process'.
src/server/server.ts(64,1): error TS2304: Cannot find name 'process'.
src/server/server.ts(66,7): error TS2304: Cannot find name 'process'.
src/server/server.ts(82,5): error TS2304: Cannot find name 'process'.
src/server/server.ts(133,5): error TS7027: Unreachable code detected.
src/server/server.ts(176,5): error TS7027: Unreachable code detected.
src/server/server.ts(190,7): error TS7027: Unreachable code detected.
src/server/server.ts(218,3): error TS2304: Cannot find name 'process'.
src/server/server.ts(218,3): error TS7027: Unreachable code detected.
src/server/server.ts(257,7): error TS2304: Cannot find name 'process'.
src/server/server.ts(258,16): error TS2304: Cannot find name 'process'.
src/util/binjson.ts(3,11): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(6,21): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(10,40): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(11,24): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(13,28): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(20,19): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(31,33): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(37,41): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(39,16): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(41,16): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(43,16): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(45,16): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(52,56): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(52,71): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(71,42): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(90,20): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(91,19): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(98,24): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(105,50): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(113,50): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(114,24): error TS2304: Cannot find name 'Buffer'.
src/util/binjson.ts(128,25): error TS2304: Cannot find name 'Buffer'.
src/util/cache.ts(21,23): error TS2307: Cannot find module 'merkle-patricia-tree'.
src/util/db.ts(20,21): error TS2307: Cannot find module 'pg-promise'.
src/util/logger.ts(21,24): error TS2307: Cannot find module 'ethereumjs-util'.
src/util/logger.ts(23,26): error TS2307: Cannot find module 'winston'.
src/util/logger.ts(24,31): error TS2307: Cannot find module 'in3-common/js/test/util/memoryLogger'.
src/util/logger.ts(26,24): error TS2307: Cannot find module 'cli-color'.
src/util/logger.ts(29,25): error TS2304: Cannot find name 'process'.
src/util/registry.ts(21,35): error TS2307: Cannot find module 'ethereumjs-util'.
src/util/registry.ts(22,33): error TS2307: Cannot find module 'in3-common'.
src/util/registry.ts(23,30): error TS2307: Cannot find module 'fs'.
src/util/registry.ts(24,26): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
src/util/registry.ts(25,24): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
src/util/sentryError.ts(20,16): error TS2304: Cannot find name 'require'.
src/util/sentryError.ts(33,13): error TS2304: Cannot find name 'process'.
src/util/tx.ts(20,26): error TS2307: Cannot find module 'ethereumjs-abi'.
src/util/tx.ts(21,63): error TS2307: Cannot find module 'ethereumjs-util'.
src/util/tx.ts(22,60): error TS2307: Cannot find module 'in3-common'.
src/util/tx.ts(24,22): error TS2307: Cannot find module 'ethereumjs-tx'.
src/util/tx.ts(26,26): error TS2307: Cannot find module '@ethersproject/abi'.
src/util/tx.ts(27,12): error TS2304: Cannot find name 'require'.
src/util/tx.ts(202,68): error TS2304: Cannot find name 'Buffer'.
test/eth/AbiCoder.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/AbiCoder.ts(25,22): error TS2307: Cannot find module 'in3-common'.
test/eth/AbiCoder.ts(30,1): error TS2304: Cannot find name 'describe'.
test/eth/AbiCoder.ts(32,3): error TS2304: Cannot find name 'it'.
test/eth/AbiCoder.ts(42,3): error TS2304: Cannot find name 'it'.
test/eth/AbiCoder.ts(63,3): error TS2304: Cannot find name 'it'.
test/eth/AbiCoder.ts(77,3): error TS2304: Cannot find name 'it'.
test/eth/convict.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/convict.ts(23,44): error TS2307: Cannot find module 'in3-common'.
test/eth/convict.ts(26,26): error TS2307: Cannot find module 'ethereumjs-util'.
test/eth/convict.ts(30,32): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
test/eth/convict.ts(31,27): error TS2307: Cannot find module 'ethers/utils'.
test/eth/convict.ts(43,34): error TS2304: Cannot find name 'Buffer'.
test/eth/convict.ts(57,1): error TS2304: Cannot find name 'describe'.
test/eth/convict.ts(59,3): error TS2304: Cannot find name 'it'.
test/eth/convict.ts(121,3): error TS2304: Cannot find name 'it'.
test/eth/convict.ts(135,3): error TS2304: Cannot find name 'it'.
test/eth/convict.ts(215,3): error TS2304: Cannot find name 'it'.
test/eth/deploy.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/deploy.ts(23,22): error TS2307: Cannot find module 'in3-common'.
test/eth/deploy.ts(24,35): error TS2307: Cannot find module 'in3'.
test/eth/deploy.ts(29,1): error TS2304: Cannot find name 'describe'.
test/eth/deploy.ts(30,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/eth_abi.ts(23,56): error TS2307: Cannot find module 'in3-common'.
test/eth/eth_abi.ts(28,25): error TS2307: Cannot find module 'in3-common/js/test/util/memoryLogger'.
test/eth/eth_abi.ts(36,1): error TS2304: Cannot find name 'describe'.
test/eth/eth_abi.ts(37,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(72,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(113,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(157,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(201,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(232,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(264,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(317,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(364,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(413,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(472,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(533,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(595,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(662,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(708,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(755,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(854,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(899,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(926,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(958,3): error TS2304: Cannot find name 'it'.
test/eth/eth_abi.ts(996,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/eth_call.ts(23,44): error TS2307: Cannot find module 'in3-common'.
test/eth/eth_call.ts(37,1): error TS2304: Cannot find name 'describe'.
test/eth/eth_call.ts(40,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(97,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(148,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(165,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(215,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(251,3): error TS2304: Cannot find name 'it'.
test/eth/eth_call.ts(286,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(21,24): error TS2307: Cannot find module 'chai'.
test/eth/features.ts(23,33): error TS2307: Cannot find module 'in3-common'.
test/eth/features.ts(26,29): error TS2307: Cannot find module 'in3/js/src/modules/eth/EthChainContext'.
test/eth/features.ts(38,1): error TS2304: Cannot find name 'describe'.
test/eth/features.ts(40,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(116,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(143,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(190,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(216,3): error TS2304: Cannot find name 'it'.
test/eth/features.ts(235,3): error TS2304: Cannot find name 'it'.
test/ipfs/ipfs.ts(21,24): error TS2307: Cannot find module 'chai'.
test/ipfs/ipfs.ts(29,24): error TS2304: Cannot find name 'process'.
test/ipfs/ipfs.ts(31,1): error TS2304: Cannot find name 'describe'.
test/ipfs/ipfs.ts(34,3): error TS2304: Cannot find name 'it'.
test/ipfs/ipfs.ts(46,3): error TS2304: Cannot find name 'it'.
test/ipfs/ipfs.ts(61,3): error TS2304: Cannot find name 'it'.
test/utils/EventWatcher.ts(20,30): error TS2307: Cannot find module 'events'.
test/utils/binData.ts(21,24): error TS2307: Cannot find module 'chai'.
test/utils/binData.ts(23,44): error TS2307: Cannot find module 'in3-common'.
test/utils/binData.ts(28,1): error TS2304: Cannot find name 'describe'.
test/utils/binData.ts(30,5): error TS2304: Cannot find name 'it'.
test/utils/binData.ts(34,5): error TS2304: Cannot find name 'it'.
test/utils/binData.ts(38,5): error TS2304: Cannot find name 'it'.
test/utils/binData.ts(43,5): error TS2304: Cannot find name 'it'.
test/utils/clientRPC.ts(2,20): error TS2307: Cannot find module 'in3'.
test/utils/transport.ts(20,49): error TS2307: Cannot find module 'in3-common'.
test/utils/transport.ts(21,20): error TS2307: Cannot find module 'in3'.
test/utils/transport.ts(25,25): error TS2307: Cannot find module 'crypto'.
test/utils/transport.ts(27,19): error TS2307: Cannot find module 'axios'.
test/utils/transport.ts(30,40): error TS2307: Cannot find module 'in3-common/js/src/util/util'.
test/utils/transport.ts(31,27): error TS2307: Cannot find module 'ethers/utils'.
test/utils/transport.ts(34,19): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(34,30): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(34,45): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(35,5): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(35,16): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(36,20): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(38,18): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(38,66): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(38,108): error TS2304: Cannot find name 'process'.
test/utils/transport.ts(232,11): error TS2304: Cannot find name 'Buffer'.
test/utils/transport.ts(233,11): error TS2304: Cannot find name 'Buffer'.

npm ERR! Linux 4.15.0-62-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! in3-server@0.1.0 build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the in3-server@0.1.0 build script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the in3-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs in3-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls in3-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ligi/git/in3/in3-node/npm-debug.log

```

**Comment by simon-jentzsch** [comment]
So with the new release this issue is fixed now. thanks.

**Comment by ligi** [comment]
I am still experiencing this error on master and develop in this repo
